# Copyright 2019 Manna Harbour
# https://github.com/manna-harbour/miryoku

CONSOLE_ENABLE=no
BOOTMAGIC_ENABLE=	no
COMMAND_ENABLE=no
EXTRAFLAGS+=-flto
LINK_TIME_OPTIMIZATION_ENABLE = yes
LTO_ENABLE = yes
BLUETOOTH_ENABLE = no

OLED_DRIVER_ENABLE = no
MAGIC_ENABLE= no%
AUDIO_ENABLE= no
SPACE_CADET_ENABLE=no 
GRAVE_ESC_ENABLE=no 
RGB_MATRIX_ENABLE = yes
RGBLIGHT_ENABLE = no%